language: python
script:
- python -m pytest
env:
  global:
    secure: qDiAW20vOO9kVjBmhkvtL/SOlFK7QLjsnd5NsXEF201DSYZOL1WsrZMD+YausQWCyt/BNioOUbL89HAnV7RCmYg3idMd8N2XL0qnvA59GL/JEyQgnjVPGt62YBWPKyJlHgt+tAh5w/60Bi4fwmVix81P9m8k0eknueVB7Fk/zOMwRF9V3KD8QmyHXehTOdwTFMFVK93zZUY/bXS511xWlkbqApYWTKL2+092re12ueH9T32qKiSm1fMOqZVpQEhUVTdT7uHYO+lElICpR9cdWv9n3QsWaz0Q2mgmQNwHGQDyct08QvH0zzwR2T2GpnqRPdG+RILZwuqc2CTsYzRaO//VvIjp6JwVmzIt82t/pWgEYFPtf8jUKJF2irHkno5xbFvX7p3d2PuRttuLKozadnemk0PLToe0afJMXQY1BwlbFcI8dT9AUAiSXfBge2yHXIywL3F/KKeGy6nc0YT/9leusFzUhQXg9PX4IRQejgNFoWZNuMDDujk1LWdAxBlfUm+YLUMeb6FqqyUTbyber+gcRgasIZcROZxNU8mpqA1Alnz8R6KQxd3Plgiof/bjwhN+jRmHwfJZDegNz6NiVINWJhxnIbRrYWPY9u3Vwa2i9bunIYkhytIhO+wWB2Ahr2n5QSvZ0ziEN7UFgiB4wNXaH+4ey3UQQ0aPMZmmQa8=
